# This is a basic workflow to help you get started with Actions

#name: Run tests with uv

# Controls when the action will run. 
#on:
#  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
  